
links = [
  {
    "id": 0,
    "name": "Anunturi",
    "link": "https://www.info.uaic.ro",
  },
  {
    "id": 1,
    "name": "Admitere",
    "link": "https://www.info.uaic.ro/admitere-2020-studii-de-licenta",
  },
  {
    "id": 2,
    "name": "Sali Libere",
    "link": "https://profs.info.uaic.ro/~orar/globale/sali_libere.html",
  },
  {
    "id": 3,
    "name": "Cazare",
    "link": "http://www.uaic.ro/studenti/cazare/",
  },
  {
    "id": 4,
    "name": "Ghidul Studentului",
    "link": "http://www.uaic.ro/studenti/ghidul-studentului-uaic/",
  },
  {
    "id": 5,
    "name": "Burse",
    "link": "http://www.uaic.ro/studenti/burse",
  },
  {
    "id": 6,
    "name": "Structura Anului",
    "link": "https://www.info.uaic.ro/academicyear1819",
  },
  {
    "id": 7,
    "name": "Orar Studenti",
    "link": "https://profs.info.uaic.ro/~orar/orar_studenti.html",
  },
  {
    "id": 8,
    "name": "Orar Profesori",
    "link": "https://profs.info.uaic.ro/~orar/orar_profesori.html",
  },
  {
    "id": 9,
    "name": "Regulamente",
    "link": "https://www.info.uaic.ro/regulamente/",
  },
  {
    "id": 10,
    "name": "ESims",
    "link": "https://simsweb.uaic.ro/eSIMS/Default.aspx",
  }
]

resources = [
  {
    "id": 0,
    "title": "Operating System",
    "description": "",
    "image_url": "https://i.ytimg.com/vi/vBURTt97EkA/sddefault.jpg",
    "link_url": "https://www.youtube.com/playlist?list=PLBlnK6fEyqRiVhbXDGLXDk_OQAeuVcp2O",
    "tag_list": "os",
  },
  {
    "id": 1,
    "title": "Linear Algebra",
    "description": "",
    "image_url": "https://i.ytimg.com/vi/kjBOesZCoqc/sddefault.jpg",
    "link_url": "https://www.youtube.com/playlist?list=PL0-GT3co4r2y2YErbmuJw2L5tW4Ew2O5B",
    "tag_list": "math",
  },
  {
    "id": 2,
    "title": "Abdul Bari",
    "description": "",
    "image_url": "https://i.postimg.cc/ZqbSJWnc/image.jpg",
    "link_url": "https://www.youtube.com/channel/UCZCFT11CWBi3MHNlGf019nw",
    "tag_list": "algorithm_design programming data_structures afcs",
  },
  {
    "id": 3,
    "title": "Tom Scott",
    "description": "",
    "image_url": "https://i.postimg.cc/R0gzhvnz/image.jpg",
    "link_url": "https://www.youtube.com/channel/UCBa659QWEk1AI4Tg--mrJ2A",
    "tag_list": "programmer_tips fun",
  },
  {
    "id": 4,
    "title": "C++",
    "description": "",
    "image_url": "https://i.ytimg.com/vi/18c3MTX0PK0/sddefault.jpg",
    "link_url": "https://www.youtube.com/playlist?list=PLlrATfBNZ98dudnM48yfGUldqGD0S4FFb",
    "tag_list": "oop",
  },
  {
    "id": 5,
    "title": "Tushar Roy - Coding Made Simple",
    "description": "",
    "image_url": "https://i.postimg.cc/wv3YsnhR/image.jpg",
    "link_url": "https://www.youtube.com/channel/UCZLJf_R2sWyUtXSKiKlyvAw",
    "tag_list": "data_structures",
  },
  {
    "id": 6,
    "title": "Google",
    "description": "",
    "image_url": "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    "link_url": "https://www.google.com/",
    "tag_list": "all",
  },
  {
    "id": 7,
    "title": "StackOverflow",
    "description": "",
    "image_url": "https://miro.medium.com/max/1200/0*UEtwA2ask7vQYW06.png",
    "link_url": "https://stackoverflow.com/",
    "tag_list": "programming",
  },
  {
    "id": 8,
    "title": "Medium",
    "description": "",
    "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Medium_logo_Wordmark_Black.svg",
    "link_url": "https://medium.com/",
    "tag_list": "article",
  },
  {
    "id": 9,
    "title": "Udemy",
    "description": "",
    "image_url": "https://www.udemy.com/staticx/udemy/images/v6/default-meta-image.png",
    "link_url": "https://www.udemy.com/",
    "tag_list": "course",
  },
  {
    "id": 10,
    "title": "Coding In Flow",
    "description": "",
    "image_url": "https://yt3.ggpht.com/a/AATXAJxBWgqGrP1UDlTUL4fF9dk2U_s0kfslRpC-TtJzJQ=s800-c-k-c0xffffffff-no-rj-mo",
    "link_url": "https://www.youtube.com/channel/UC_Fh8kvtkVPkeihBs42jGcA",
    "tag_list": "android"
  },
  # {
  #   "id": 0,
  #   "title": "Coding With Mitch",
  #   "description": "",
  #   "image_url": "",
  #   "link_url": "",
  #   "tag_list": ""
  # },

]

classes = [
  {
    "id": 0,
    "name": "Data Structures",
    "name_short": "DS",
    "credits": 6,
    "material_link": "http://bit.ly/38xJkry",
    "site_link": "https://profs.info.uaic.ro/~sd",
    "site_password": "sd sd20192020",
    "year": 1,
    "semester": 1,
  },

  {
    "id": 1,
    "name": "Computer Architecture and Operating Systems",
    "name_short": "CAOS",
    "credits": 5,
    "material_link": "http://bit.ly/31PbY5b",
    "site_link": "https://profs.info.uaic.ro/~rvlad/stud.html",
    "site_password": "",
    "year": 1,
    "semester": 1,
  },
  {
    "id": 2,
    "name": "Logics for Computer Science",
    "name_short": "Logics",
    "credits": 6,
    "material_link": "http://bit.ly/2SnbW14",
    "site_link": "https://profs.info.uaic.ro/~rvlad/stud.html",
    "site_password": "",
    "year": 1,
    "semester": 1,
  },
  {
    "id": 3,
    "name": "Mathematics",
    "name_short": "Math",
    "credits": 5,
    "material_link": "http://bit.ly/2UQg7Eq",
    "site_link": "https://profs.info.uaic.ro/~andreea.arusoaie/mate.html",
    "site_password": "",
    "year": 1,
    "semester": 1,
  },
  {
    "id": 4,
    "name": " Introduction to Programming",
    "name_short": "IP",
    "credits": 4,
    "material_link": "http://bit.ly/31NKKvN",
    "site_link": "http://www.edusoft.ro/introp",
    "site_password": "",
    "year": 1,
    "semester": 1
  },
  {
    "id": 5,
    "name": "English Language I",
    "name_short": "English",
    "credits": 4,
    "material_link": "",
    "site_link": "https://profs.info.uaic.ro/~augusto.perez",
    "site_password": "",
    "year": 1,
    "semester": 1
  },
  {
    "id": 6,
    "name": "Competitive Programming V",
    "name_short": "CP",
    "credits": 3,
    "material_link": "",
    "site_link": "http://students.info.uaic.ro/~alexandru.ionita/pc/index.html",
    "site_password": "",
    "year": 1,
    "semester": 1
  },
  {
    "id": 7,
    "name": "Physical Education I",
    "name_short": "FE",
    "credits": 1,
    "material_link": "",
    "site_link": "",
    "site_password": "",
    "year": 1,
    "semester": 1
  },
  {
    "id": 8,
    "name": "Educational Psychology",
    "name_short": "EP",
    "credits": 5,
    "material_link": "",
    "site_link": "",
    "site_password": "",
    "year": 1,
    "semester": 1
  },

  {
    "id": 9,
    "name": "Object Oriented Programming",
    "name_short": "OOP",
    "credits": 6,
    "material_link": "http://bit.ly/39Wbspf",
    "site_link": "https://sites.google.com/site/fiicoursepoo",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 10,
    "name": "Operating Systems",
    "name_short": "OS",
    "credits": 6,
    "material_link": "http://bit.ly/2ISTg3W",
    "site_link": "https://profs.info.uaic.ro/~vidrascu/SO",
    "site_password": "so2020 1+2=3",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 11,
    "name": "Algebraic Foundations of Computer Science",
    "name_short": "AFCS",
    "credits": 5,
    "material_link": "http://bit.ly/2TT0zyW",
    "site_link": "https://profs.info.uaic.ro/~fltiplea/AFCS/AFCS.html",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 12,
    "name": "Probabilities and Statistics",
    "name_short": "PS",
    "credits": 4,
    "material_link": "http://bit.ly/2ITqL6g",
    "site_link": "https://profs.info.uaic.ro/~adrian.zalinescu/PS.html",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 13,
    "name": "Algorithms Design",
    "name_short": "AD",
    "credits": 5,
    "material_link": "http://bit.ly/2UafO5w",
    "site_link": "https://sites.google.com/site/fiicoursepa",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 14,
    "name": "English Language II",
    "name_short": "English",
    "credits": 4,
    "material_link": "",
    "site_link": "https://profs.info.uaic.ro/~augusto.perez",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 15,
    "name": "Competitive Programming VI",
    "name_short": "CP",
    "credits": 3,
    "material_link": "",
    "site_link": "http://students.info.uaic.ro/~alexandru.ionita/pc/index.html",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 16,
    "name": "Physical Education II",
    "name_short": "FE",
    "credits": 1,
    "material_link": "",
    "site_link": "",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 17,
    "name": "Ethics and Academic Integrity",
    "name_short": "EP",
    "credits": 3,
    "material_link": "",
    "site_link": "",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },
  {
    "id": 18,
    "name": "Pedagogy I",
    "name_short": "EP",
    "credits": 5,
    "material_link": "",
    "site_link": "",
    "site_password": "",
    "year": 1,
    "semester": 2,
  },


  {
    "id": 19,
    "name": "Second Year Coming Soon",
    "name_short": "OS",
    "credits": 6,
    "material_link": "",
    "site_link": "",
    "site_password": "",
    "year": 2,
    "semester": 1,
  },

  {
    "id": 20,
    "name": "Third Year Coming Soon",
    "name_short": "OS",
    "credits": 6,
    "material_link": "",
    "site_link": "",
    "site_password": "",
    "year": 3,
    "semester": 1,
  },
]

